import bodyParser from 'body-parser';
import debounce from 'debounce';
import { app, errorHandler } from 'mu';
import { filterDeltaForInsertedType } from './lib/delta';
import linkStaatsblad from './queries/select-without-uuid';

const LEGAL_RESOURCE = 'http://data.europa.eu/eli/ontology#LegalResource';

const debouncedLinkStaatsblad = debounce(linkStaatsblad, 30 * 1000); // In case of delta's generated by batch import, wait until import is done.

app.post('/run', async (req, res) => {
  linkStaatsblad();
});

app.post('/delta', bodyParser.json(), async (req, res) => {
  res.status(202).end();
  const insertedSubjects = filterDeltaForInsertedType(req.body, LEGAL_RESOURCE);
  if (insertedSubjects.length > 0) {
    console.log(`Received ${insertedSubjects.length} object inserts of type <${LEGAL_RESOURCE}> through delta's. Handling now.`);
    debouncedLinkStaatsblad();
  }
});

app.use(errorHandler);
