import bodyParser from 'body-parser';
import debounce from 'debounce';
import { app, errorHandler } from 'mu';
import { filterDeltaForInsertedPredicates } from './lib/delta';
import { linkStaatsblad } from './queries/link-staatsblad';

const NUMAC_PREDICATES = [
  'http://data.europa.eu/eli/ontology#id_local',
  'http://www.w3.org/2004/02/skos/core#notation'
];

const debouncedLinkStaatsblad = debounce(linkStaatsblad, 30 * 1000); // In case of delta's generated by batch import, wait until import is done.

app.post('/run', async (req, res) => {
  linkStaatsblad();
});

app.post('/delta', bodyParser.json(), async (req, res) => {
  res.status(202).end();
  const insertedSubjects = filterDeltaForInsertedPredicates(req.body, NUMAC_PREDICATES);
  if (insertedSubjects.length > 0) {
    console.log(`Received ${insertedSubjects.length} matching inserts through delta's. Handling now.`);
    debouncedLinkStaatsblad();
  }
});

app.use(errorHandler);
